version: '3'

services:
  libraryservice:
    image: library-service
    container_name: library-service
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - postgres_services
    ports:
      - 8000:8000

networks:
  postgres_services:
    external: true
    name: postgres_services
